const products = [
  {
    name: "Athletic Fit T-Shirt",
    slug: "athletic-fit-tshirt",
    description: "High-performance athletic t-shirt with breathable fabric.",
    price: 29.99,
    isActive: true,
    category: "T-Shirts",
     gender:'male',
    sizes: ["S", "M", "L", "XL"],
    countInStock: 20,
    image: "https://media.istockphoto.com/id/1469916091/photo/woman-warming-up-for-a-morning-workout-outdoors.jpg?s=1024x1024&w=is&k=20&c=cRXUAKJnjxNsFaMZuIdMKm32wQILJsOqTFsdrZW5MaQ=",
    link: "/products/athletic-fit-tshirt",
  },
  {
    name: "Seamless Leggings",
    isActive: true,
    slug: "seamless-leggings",
    description: "Comfortable seamless leggings for high mobility.",
    price: 39.99,
    category: "Leggings",
     gender:'male',
    sizes: ["S", "M", "L"],
    countInStock: 15,
    image: "https://media.istockphoto.com/id/588615220/photo/fitness-girl-exercising-with-dumbbells-on-a-dark-background.jpg?s=1024x1024&w=is&k=20&c=x64U8Ae3eI0dgITfo4BV_xwtRijw2J4nskPVAnjdcUc=",
    link: "/products/seamless-leggings",
  },
  {
    name: "Muscle Tank",
    slug: "muscle-tank",
    description: "Sleeveless tank designed for comfort and movement.",
    price: 24.99,
    isActive: true,
     gender: 'male',
    category: "Tanks",
    sizes: ["M", "L", "XL"],
    countInStock: 30,
    image: "https://images.unsplash.com/photo-1530822847156-5df684ec5ee1?w=600&auto=format&fit=crop&q=60",
    link: "/products/muscle-tank",
  },
  {
    name: "Performance Hoodie",
    slug: "performance-hoodie",
    description: "Warm and stretchable hoodie perfect for workouts.",
    price: 49.99,
    isActive: true,
     gender:  'male',
    category: "Hoodies",
    sizes: ["S", "M", "L", "XL"],
    countInStock: 10,
    image: "https://images.unsplash.com/photo-1648484860115-906abc06a59a?q=80&w=1974&auto=format&fit=crop",
    link: "/products/performance-hoodie",
  },
  {
    name: "Compression Shorts",
    slug: "compression-shorts",
    description: "Supportive compression shorts for training sessions.",
    price: 19.99,
     gender:  'male',
    isActive: true,
    category: "Shorts",
    sizes: ["S", "M", "L"],
    countInStock: 25,
    image: "https://images.unsplash.com/photo-1602135918313-aff25ed7dc98?q=80&w=2070&auto=format&fit=crop",
    link: "/products/compression-shorts",
  },
  {
    name: "Crop Top Tee",
    slug: "crop-top-tee",
    description: "Fashionable crop top tee with a slim fit.",
    price: 22.99,
    isActive: true,
     gender:  'male',
    category: "T-Shirts",
    sizes: ["XS", "S", "M"],
    countInStock: 12,
    image: "https://images.unsplash.com/photo-1618378898259-53b30e703ba3?q=80&w=2070&auto=format&fit=crop",
    link: "/products/crop-top-tee",
  },
  {
    name: "Sports Bra - Medium Support",
    slug: "sports-bra-medium",
    description: "Medium support bra with racerback design.",
    price: 34.99,
    isActive: true,
     gender:  'male',
    category: "Bras",
    sizes: ["S", "M", "L"],
    countInStock: 18,
    image: "https://images.unsplash.com/photo-1530822847156-5df684ec5ee1?w=600&auto=format&fit=crop&q=60",
    link: "/products/sports-bra-medium",
  },
  {
    name: "Jogger Pants",
    slug: "jogger-pants",
    description: "Slim fit joggers with an athletic look.",
    price: 44.99,
    isActive: true,
     gender:  'male',
    category: "Joggers",
    sizes: ["S", "M", "L", "XL"],
    countInStock: 22,
    image: "https://images.unsplash.com/photo-1526401485004-6f50a2953e0e?w=600&auto=format&fit=crop&q=60",
    link: "/products/jogger-pants",
  },
  {
    name: "Sleeveless Hoodie",
    slug: "sleeveless-hoodie",
    description: "Hoodie without sleeves for active workouts.",
    price: 32.99,
    isActive: true,
     gender:  'male',
    category: "Hoodies",
    sizes: ["M", "L", "XL"],
    countInStock: 17,
    image: "https://images.unsplash.com/photo-1541529086526-781bfb132a84?w=600&auto=format&fit=crop&q=60",
    link: "/products/sleeveless-hoodie",
  },
  {
    name: "Mesh Panel Leggings",
    slug: "mesh-panel-leggings",
    description: "Stylish leggings with breathable mesh inserts.",
    price: 42.99,
    isActive: true,
     gender:  'male',
    category: "Leggings",
    sizes: ["S", "M", "L"],
    countInStock: 14,
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=600&auto=format&fit=crop&q=60",
    link: "/products/mesh-panel-leggings",
  },
  {
    name: "Oversized Gym Tee",
    slug: "oversized-gym-tee",
    description: "Loose fit t-shirt perfect for training.",
    price: 27.99,
     gender:  'male',
    isActive: true,
    category: "T-Shirts",
    sizes: ["M", "L", "XL"],
    countInStock: 26,
    image: "https://images.unsplash.com/photo-1514996937319-344454492b37?w=600&auto=format&fit=crop&q=60",
    link: "/products/oversized-gym-tee",
  },
  {
    name: "V-Back Sports Bra",
    slug: "v-back-sports-bra",
    description: "Supportive bra with elegant V-back.",
    price: 36.99,
    isActive: true,
     gender:  'male',
    category: "Bras",
    sizes: ["S", "M", "L"],
    countInStock: 19,
    image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=60",
    link: "/products/v-back-sports-bra",
  },
  {
    name: "Quick-Dry Shorts",
    slug: "quick-dry-shorts",
    description: "Moisture-wicking shorts for sweaty sessions.",
    price: 21.99,
    isActive: true,
     gender:  'male',
    category: "Shorts",
    sizes: ["S", "M", "L", "XL"],
    countInStock: 28,
    image: "https://images.unsplash.com/photo-1514513874978-064cb8e281e3?w=600&auto=format&fit=crop&q=60",
    link: "/products/quick-dry-shorts",
  },
  {
    name: "Fleece Zip Hoodie",
    slug: "fleece-zip-hoodie",
    description: "Cozy fleece hoodie with full zip and pockets.",
    price: 54.99,
    isActive: true,
     gender:  'male',
    category: "Hoodies",
    sizes: ["M", "L", "XL", "XXL"],
    countInStock: 16,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b4?w=600&auto=format&fit=crop&q=60",
    link: "/products/fleece-zip-hoodie",
  },
  {
    name: "Cut-Off Sleeveless Tee",
    slug: "cut-off-tee",
    description: "Raw-edged cut-off tee for upper body days.",
    price: 23.99,
    category: "Tanks",
     gender:  'male',
    sizes: ["M", "L", "XL"],
    countInStock: 24,
    image: "https://images.unsplash.com/photo-1533658925621-4c2b24f6a445?w=600&auto=format&fit=crop&q=60",
    link: "/products/cut-off-tee",
  },
  {
    name: "High Rise Biker Shorts",
    slug: "biker-shorts-high-rise",
    description: "High-rise shorts with flattering contour seams.",
    price: 25.99,
    isActive: true,
     gender:  'male',
    category: "Shorts",
    sizes: ["S", "M", "L"],
    countInStock: 21,
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=60",
    link: "/products/biker-shorts-high-rise",
  },
  {
    name: "Tie-Dye Leggings",
    slug: "tie-dye-leggings",
    description: "Bold print leggings for stylish workouts.",
    price: 38.99,
    isActive: true,
     gender:  'male',
    category: "Leggings",
    sizes: ["S", "M", "L"],
    countInStock: 11,
    image: "https://images.unsplash.com/photo-1531966667228-45c0f9f99236?w=600&auto=format&fit=crop&q=60",
    link: "/products/tie-dye-leggings",
  },
  {
    name: "Racerback Tank",
    slug: "racerback-tank",
    description: "Lightweight tank with racerback style.",
    price: 20.99,
    isActive: true,
     gender:  'male',
    category: "Tanks",
    sizes: ["S", "M", "L"],
    countInStock: 29,
    image: "https://images.unsplash.com/photo-1517964603305-cf4b9d4ee47a?w=600&auto=format&fit=crop&q=60",
    link: "/products/racerback-tank",
  },
  {
    name: "Thermal Compression Shirt",
    slug: "thermal-compression-shirt",
    description: "Thermal fabric compression shirt for cold days.",
    price: 45.99,
    isActive: true,
     gender:  'male',
    category: "T-Shirts",
    sizes: ["M", "L", "XL"],
    countInStock: 13,
    image: "https://images.unsplash.com/photo-1526401485004-6f50a2953e0e?w=600&auto=format&fit=crop&q=60",
    link: "/products/thermal-compression-shirt",
  },
  {
    name: "Track Jacket",
    slug: "track-jacket",
    description: "Lightweight track jacket with zipper.",
    price: 52.99,
    isActive: true,
     gender:  'male',
    category: "Jackets",
    sizes: ["S", "M", "L", "XL"],
    countInStock: 18,
    image: "https://images.unsplash.com/photo-1514996937319-344454492b37?w=600&auto=format&fit=crop&q=60",
    link: "/products/track-jacket",
  },
  {
    name: "Mesh Hoodie",
    slug: "mesh-hoodie",
    description: "Breathable mesh hoodie for warm-ups.",
    price: 44.99,
    isActive: true,
     gender:  'male',
    category: "Hoodies",
    sizes: ["M", "L", "XL"],
    countInStock: 20,
    image: "https://images.unsplash.com/photo-1541529086526-781bfb132a84?w=600&auto=format&fit=crop&q=60",
    link: "/products/mesh-hoodie",
  },
  {
    name: "Lightweight Running Shorts",
    slug: "running-shorts-lightweight",
    description: "Minimalistic shorts with quick dry fabric.",
    price: 22.99,
     gender:  'male',
    isActive: true,
    category: "Shorts",
    sizes: ["S", "M", "L"],
    countInStock: 23,
    image: "https://images.unsplash.com/photo-1514513874978-064cb8e281e3?w=600&auto=format&fit=crop&q=60",
    link: "/products/running-shorts-lightweight",
  },
];
export default products