export const products = [
  {
    id: "1",
    name: "Performance T-Shirt",
    price: 29.99,
    query: "gym tshirt",
    description: "Lightweight, breathable, and perfect for workouts.",
  },
  {
    id: "2",
    name: "Gym Hoodie",
    price: 49.99,
    query: "gym hoodie",
    description: "Stay warm before and after your gym session.",
  },
  {
    id: "3",
    name: "Compression Shorts",
    price: 24.99,
    query: "gym shorts",
    description: "Supports performance with maximum flexibility.",
  },
  {
    id: "4",
    name: "Workout Leggings",
    price: 34.99,
    query: "leggings fitness",
    description: "Sleek and stretchable fabric for optimal movement.",
  },
  {
    id: "5",
    name: "Mesh Tank Top",
    price: 22.99,
    query: "tanktop gym",
    description: "Ultra-light tank designed for intense sessions.",
  },
  {
    id: "6",
    name: "Zipper Jacket",
    price: 59.99,
    query: "sports jacket",
    description: "Stylish and practical for any season.",
  },
  {
    id: "7",
    name: "Training Joggers",
    price: 39.99,
    query: "joggers fitness",
    description: "Sweat-wicking and slim-fit design for comfort.",
  },
  {
    id: "8",
    name: "High Impact Sports Bra",
    price: 27.99,
    query: "sportsbra workout",
    description: "Support and style combined for active wear.",
  },
  {
    id: "9",
    name: "Seamless Shorts",
    price: 26.99,
    query: "gym shorts women",
    description: "Friction-free comfort for daily routines.",
  },
  {
    id: "10",
    name: "Cotton Oversized Tee",
    price: 19.99,
    query: "oversized tshirt",
    description: "Comfy and casual with an athletic edge.",
  },
  {
    id: "11",
    name: "Flex Fit Cap",
    price: 14.99,
    query: "cap fitness",
    description: "Sun protection and cool style on the go.",
  },
  {
    id: "12",
    name: "Activewear Socks (3 Pack)",
    price: 12.99,
    query: "socks sports",
    description: "Supportive ankle socks for everyday training.",
  },
  {
    id: "13",
    name: "Muscle Fit Tank",
    price: 25.99,
    query: "tank gym",
    description: "Tapered for definition and movement.",
  },
  {
    id: "14",
    name: "Lightweight Windbreaker",
    price: 45.99,
    query: "windbreaker jacket",
    description: "Built to block wind without overheating.",
  },
  {
    id: "15",
    name: "Stretch Training Tee",
    price: 28.49,
    query: "stretch tshirt",
    description: "Freedom of movement in every lift.",
  },
  {
    id: "16",
    name: "Grip Workout Gloves",
    price: 17.99,
    query: "gym gloves",
    description: "Protect your hands and boost grip.",
  },
  {
    id: "17",
    name: "Sleeveless Hoodie",
    price: 32.99,
    query: "sleeveless hoodie",
    description: "Style and airflow in one look.",
  },
  {
    id: "18",
    name: "Cropped Gym Top",
    price: 21.99,
    query: "croptop workout",
    description: "Made for active women with style.",
  },
  {
    id: "19",
    name: "Track Suit Set",
    price: 69.99,
    query: "tracksuit fitness",
    description: "Complete 2-piece for training and travel.",
  },
  {
    id: "20",
    name: "Classic Fit T-Shirt",
    price: 18.99,
    query: "classic tshirt gym",
    description: "Timeless fit and feel for everyday workouts.",
  },
];
